https://www.youtube.com/watch?v=5Ym-dOS9ssA&list=PLhhyoLH6IjfxVOdVC1P1L5z5azs0XjMsb
video 3

In [2]:
import tensorflow as tf

In [71]:
physical_devices=tf.config.list_physical_devices('GPU')
#tf.config.experimental.set_memory_growth(physical_devices[1],True)

In [2]:
print(tf.__version__)

2.13.0


Tensor:Form a programming perspective , a tensor is a multidimensional array that has ability to run on GPU

In [3]:
x=tf.constant(4)

In [4]:
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
x=tf.constant(4.0)

In [6]:
print(x)

tf.Tensor(4.0, shape=(), dtype=float32)


In [7]:
x=tf.constant(4,shape=(1,1),dtype=tf.float32)

In [8]:
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [15]:
x=tf.constant([[1,2,3],[4,5,6]],shape=(2,3))

In [16]:
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [17]:
x=tf.ones((3,3))

In [18]:
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [19]:
x=tf.zeros((2,3))

In [20]:
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [21]:
x=tf.eye(3)

In [22]:
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [3]:
x=tf.random.normal((2,3,4),mean=0,stddev=1)

In [4]:
print(x)

tf.Tensor(
[[[ 0.21478361 -0.86415917  1.266198   -0.4470239 ]
  [ 1.2907151   1.0018272  -0.478398    0.25391835]
  [-1.7501918  -1.6734685   0.08509771 -0.64854556]]

 [[ 0.07341845  1.4977173   0.11266054 -2.2029867 ]
  [-1.0703428   0.65042627 -0.38715288 -0.9559728 ]
  [ 0.7388649  -0.45263082 -1.2940228  -0.38537347]]], shape=(2, 3, 4), dtype=float32)


In [26]:
x[1]

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.04892362, -0.0967765 , -0.04448722,  0.5181608 ],
       [ 1.413146  ,  0.38442782, -1.8361334 ,  0.250824  ],
       [-0.08258942,  0.7108245 ,  0.13029942,  1.6027954 ]],
      dtype=float32)>

In [30]:
x[0,1]

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.60581136, 0.04235029, 0.02255724, 0.40679172], dtype=float32)>

In [31]:
x=tf.random.uniform((1,3),minval=0,maxval=1)

In [32]:
print(x)

tf.Tensor([[0.10629737 0.96291804 0.03338659]], shape=(1, 3), dtype=float32)


In [33]:
x=tf.range(9)

In [34]:
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [40]:
x=tf.range(start=1,limit=10,delta=2)

In [41]:
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [42]:
x=tf.cast(x,dtype=tf.float64)

In [43]:
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [44]:
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])

In [45]:
z=tf.add(x,y)

In [46]:
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [47]:
z=x+y

In [48]:
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [51]:
z=tf.subtract(x,y)
z=x-y

In [52]:
z=tf.divide(x,y)

In [53]:
z=x/y

In [54]:
z=tf.multiply(x,y)

In [55]:
z=x*y

In [61]:
z=tf.tensordot(x,y,axes=1)

In [62]:
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [63]:
z=tf.reduce_sum(x*y,axis=0)

In [64]:
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [65]:
z=x**5

In [66]:
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [77]:
x=tf.random.normal((2,3))
y=tf.random.normal((3,4))


In [ ]:
z=tf.matmul(x,y)

In [78]:
z=x@y
print(z)

tf.Tensor(
[[0.9017019  1.6444894  2.0779538  0.93692476]
 [1.7208606  0.92470896 0.59651667 0.2128017 ]], shape=(2, 4), dtype=float32)


In [79]:
x=tf.constant([0,1,1])

#ındexing

In [80]:
x=tf.constant([0,1,1,2,3,1,2,3])

In [81]:
print(x[:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)


In [82]:
print(x[1:])

tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)


In [83]:
print(x[1:3])

tf.Tensor([1 1], shape=(2,), dtype=int32)


In [85]:
print(x[::2])

tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)


In [86]:
print(x[::-1])

tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [87]:
indices=tf.constant([0,3])

In [88]:
x_ind=tf.gather(x,indices)

In [89]:
print(x_ind)

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [92]:
x=tf.constant([[1,2],
              [3,4],
              [5,6]])

In [93]:
print(x[0])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [94]:
print(x[0,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [95]:
print(x[0:2,])

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


#Reshaping

In [103]:
x=tf.range(9)

In [104]:
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [105]:
x=tf.reshape(x,(3,3))

In [106]:
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [107]:
x=tf.transpose(x,perm=[1,0])

In [108]:
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
